name: Build Project for Windows 🖥️

on: 
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:          
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Restore Library cache
        uses: actions/cache@v4.2.1
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4.3.0
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build - Windows
          path: build/StandaloneWindows64
