name: Build Project for Windows and Android

on:
  workflow_dispatch:

#env:
#  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  testRunner:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode: [EditMode, PlayMode]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Restore Library cache
        uses: actions/cache@v4.2.1
        with:
          path: Library
          key: Library-test-${{ matrix.testMode }}
          restore-keys: |
            Library-test-
            Library-

      - name: Run Unity Test Runner
        uses: game-ci/unity-test-runner@v4.3.1
        id: testRunner
        with:
          testMode: ${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Test Results - ${{ matrix.testMode }}
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  buildWindows:
    needs: testRunner
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Restore Library cache
        uses: actions/cache@v4.2.1
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4.3.0
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build - Windows
          path: build/StandaloneWindows64

  buildAndroid:
    needs: testRunner
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Restore Library cache
        uses: actions/cache@v4.2.1
        with:
          path: Library
          key: Library-build-Android
          restore-keys: |
            Library-build-
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4.3.0
        with:
          targetPlatform: Android

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build - Android
          path: build/Android
